# Generated by Django 3.0.6 on 2020-05-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblogs',
            name='image',
            field=models.ImageField(upload_to='my_blog/images'),
        ),
    ]
