# Generated by Django 3.0.6 on 2020-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_auto_20200511_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogs',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='myblogs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myblogs',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
