# Generated by Django 3.0.6 on 2020-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='image',
            field=models.ImageField(upload_to='my_portfolio/images'),
        ),
    ]
